services:
  # 1. The Web Service (Express API)
  - type: web
    name: inventory-api
    runtime: node
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: PORT
        value: 3000
      - key: DB_USER
        fromDatabase:
          name: inventory-db
          property: user
      - key: DB_HOST
        fromDatabase:
          name: inventory-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: inventory-db
          property: database
      - key: DB_PASSWORD
        fromDatabase:
          name: inventory-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: inventory-db
          property: port
      - key: REDIS_URL
        sync: false # Set manually via Dashboard (from Upstash)
      - key: RABBITMQ_URL
        sync: false # Set manually via Dashboard (from CloudAMQP)

  # 2. The Background Worker (Queue Processor)
  - type: worker
    name: inventory-worker
    runtime: node
    buildCommand: npm install
    startCommand: node worker.js
    envVars:
      - key: DB_USER
        fromDatabase:
          name: inventory-db
          property: user
      - key: DB_HOST
        fromDatabase:
          name: inventory-db
          property: host
      - key: DB_NAME
        fromDatabase:
          name: inventory-db
          property: database
      - key: DB_PASSWORD
        fromDatabase:
          name: inventory-db
          property: password
      - key: DB_PORT
        fromDatabase:
          name: inventory-db
          property: port
      - key: REDIS_URL
        sync: false 
      - key: RABBITMQ_URL
        sync: false

databases:
  - name: inventory-db
    plan: free
